---
name: eso-config-ci
"on":
  push:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test
